name: "Slash Command Approveal Checker"
author: "NickLiffen"
description: "Slash Command Approval Check GitHub Action"
inputs:
  fileURI:
    description: "The relative URI path to the yml file storing people who can approve a PoC"
    required: true
  commandUser:
    description: "The GitHub Username who executed the command"
    required: true
outputs:
  approved:
    description: "true means yes, false means no"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "target"
  color: "blue"
