name: "Testing"
on: [push]
jobs:
  integ:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Running an Approved Action (User)
        id: positiveTest
        uses: ./
        with:
          fileURI: ".github/workflows/example-inputs/file.yml"
          commandUser: "NickLiffen"
          response: "true"
      - name: See Results from the Approved Actions (User)
        run: |
          echo ${{ steps.positiveTest.outputs.approved }}
      - name: Running a Non Approved Action (User)
        id: negativeTest
        uses: ./
        with:
          fileURI: ".github/workflows/example-inputs/file.yml"
          commandUser: "@BobTheBuilder"
          response: "true"
      - name: See Results from the Non-Approved Actions (User)
        run: |
          echo ${{ steps.negativeTest.outputs.approved }}
      - name: Running a Non Approved Action (Response)
        id: negativeTestResponse
        uses: ./
        with:
          fileURI: ".github/workflows/example-inputs/file.yml"
          commandUser: "@NickLiffen"
          response: "false"
      - name: See Results from the Non-Approved Actions (Response)
        run: |
          echo ${{ steps.negativeTestResponse.outputs.approved }}